name: Configuration

on: 
  pull_request:
  push:
    branches: ['**']
    branches-ignore: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm ci
      - name: linting js
        run: npm run lint:js
      - name: linting css
        run: npm run lint:css
      - name: build
        run: npm run build


